# Generated by Django 5.2.7 on 2025-10-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_ONG', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
